org: andrewsosa
app: ghtrends-commits
service: ghtrends-commits

frameworkVersion: "2"
useDotenv: false
# variablesResolutionMode: 20210326

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

functions:
  index:
    handler: api/main.handler
    events:
      - http:
          path: /
          method: get
  etl:
    handler: api/etl.handler
    timeout: 600
    # events:
    #   - http:
    #       path: /etl
    #       method: get

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:AWS_S3_BUCKET_NAME}
